# Generated by Django 5.2.6 on 2025-09-22 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_initial'),
        ('recetas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.familia'),
        ),
        migrations.AddField(
            model_name='historicoreceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta'),
        ),
        migrations.AddField(
            model_name='recetaproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='recetaproducto',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta'),
        ),
        migrations.AddField(
            model_name='receta',
            name='productos',
            field=models.ManyToManyField(through='recetas.RecetaProducto', to='productos.producto'),
        ),
    ]
