# Generated by Django 5.2.6 on 2025-09-22 23:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompraProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(verbose_name=django.utils.timezone.now)),
                ('cantidad_comprada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('unidad_medida', models.CharField(choices=[('Ml', 'Mililitos'), ('Kg', 'Kilogramos'), ('U', 'Unidad')], default='U', max_length=10)),
            ],
        ),
    ]
