# Generated by Django 5.2.6 on 2025-09-22 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraproducto',
            name='fecha_compra',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
