# Generated by Django 5.2.6 on 2025-09-22 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.familia'),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
